openapi: 3.0.3
info:
  title: Bank Argent Transactions API documentation
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  version: 1.0.11

servers:
  - url: http://localhost:3001/api/v1

tags:
  - name: Transactions
    description: Everything about your Transactions
  - name: Transaction Details
    description: Details about individual transactions
  - name: Information Details
    description: Update information for transactions

paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Transactions
      description: Get all transactions for the current month, grouped by account
      security:
        - Bearer: []  
      responses:
        '200':
          description: User Profile's transactions retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTransactions'
        '401':
          description: User unathorized. Authentification is required.
          content:
            application/json:
              example:
                error:  User Unauthenticated. Authentification is required
        '404':
          description: No transactions found for the user or invalid profile
          content:
           application/json:
             example:
              error: Transactions not found or invalid profile.
        '500':
         description: Internal server error.
         content:
           application/json:
            example:
              error: An internal server error occurred.

    parameters:
      - in: header
        name: Auth
        description: Attach Bearer JWT token
        required: true
        schema: 
          type: string

  /transactions/{id}/details:
    get:
      tags:
        - Transaction Details
      summary: Get details of a transaction.
      description: Details of a transaction.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the transaction retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDetails'
        '404':
         description: Transaction not found or invalid transaction ID.
         content:
          application/json:
            example:
              error: Transaction not found.
        '500':
         description: Internal server error.
         content:
           application/json:
            example:
              error: An internal server error occurred.

  /transactions/{id}/category:
    patch:
      tags:
        - Information Details
      summary: Update information of a specific transaction.
      description: Update category using a dropdown selection.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated category for the transaction.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdateCategory'
      responses:
       '200':
        description: Category updated successfully.
        content:
          application/json:
            example:
              message: Category updated successfully.
       '404':
        description: Transaction not found or invalid transaction ID.
        content:
          application/json:
            example:
              error: Transaction not found.
       '500':
        description: Internal server error.
        content:
          application/json:
            example:
              error: An internal server error occurred.

  /transactions/{id}/notes:
    patch:
      tags:
        - Information Details
      summary: Update information of a specific transaction.
      description: Update notes by direct input.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated notes for the transaction.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdateNotes'
      responses:
       '200':
        description: Notes updated successfully.
        content:
          application/json:
            example:
              message: Notes updated successfully.
       '404':
        description: Transaction not found or invalid transaction ID.
        content:
          application/json:
            example:
              error: Transaction not found.
       '500':
        description: Internal server error.
        content:
          application/json:
            example:
              error: An internal server error occurred.

components:
  schemas:
    UserTransactions:
      type: object
      properties:
        availableBalance:
          type: number
          format: float
          description: Balance of the last transaction.
        transactions:
          type: object
          properties:
            date: 
              type: string
              format: date-time
              description: Date of the transaction
            description:
              type: string
              description: Description of the transaction.
            amount:
              type: number
              format: float
              description: Amount of the transaction.
            balance:
              type: number
              format: float
              description: Balance after the transaction  
    TransactionDetails:
      type: object
      properties:
        date:
          type: string
          format: date-time
          description: Date of the transaction.
        description:
          type: string
          description: Description of the transaction.
        amount:
          type: number
          format: float
          description: Amount of the transaction.
        balance:
          type: number
          format: float
          description: Balance after the transaction.
        category:
          type: string
          description: Category of the transaction.
        notes:
          type: string
          description: Additional note for the transaction.

    TransactionUpdateCategory:
      type: object
      properties:
        category:
          type: string
          description: Category of the transaction.
          enum:
            - 'Food'
            - 'Assurance'
            - 'Other'

    TransactionUpdateNotes:
      type: object
      properties:
        notes:
          type: string
          description: Additional note for the transaction.

  securitySchemes:
    Bearer:  
      type: apiKey
      name: Authorization
      in: header